targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
          any_map: false
          checked: false
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          field_rename: none
          ignore_unannotated: false
          include_if_null: true
      retrofit_generator:
        options:
          auto_cast_response: true
          parser: json_serializable 