name: plateforme_universitaire
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State management and routing
  get: ^4.6.6
  provider: ^6.1.1

  # HTTP and networking
  dio: ^5.4.0
  retrofit: ^4.1.0
  http: ^1.1.0

  # JSON serialization
  json_annotation: ^4.8.1

  # Storage and preferences
  flutter_secure_storage: ^9.0.0
  get_storage: ^2.1.1

  # UI components
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.5.0
  carousel_slider: ^5.0.0
  badges: ^3.1.2
  lottie: ^2.6.0
  rive: ^0.11.4
  cupertino_icons: ^1.0.2
  animated_background: ^2.0.0

  # Utilities
  intl: ^0.18.1
  file_picker: ^10.1.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/background.jpeg
    - assets/images/login.jpeg
    - assets/images/amphi.jpg
    - assets/images/procedures.jpeg
    - assets/images/student.jpeg
    - assets/images/maintenance.jpeg
    - assets/images/web.webp
    - assets/images/tech.jpg
    - assets/images/graduation.jpg
    - assets/images/black.webp
    - assets/images/avatar.jpeg
    - assets/images/enseignant.jpg
    - assets/images/admin.jpeg
    - assets/images/form.avif
    - assets/images/form.jpg
    - assets/images/chat.html

dev_dependencies:
  # Code generation
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.6
  source_gen: ^1.5.0

  # Testing
  flutter_test:
    sdk: flutter

  # Development utilities
  change_app_package_name: ^1.1.0

  # Pusher
  pusher_channels_flutter: ^2.4.0